Amp is a command-line interface to YouTube that lets you play music with minimal disturbance to your workflow.  It takes arguments in the form of YouTube search terms and plays the first result in a background process.

* Usage
#+BEGIN_EXAMPLE
$ amp sotc ost
Now playing: Shadow of the Colossus OST (Playstation 2) [01:15:51]

$ amp
Playback paused. Type 'amp' again to resume.

$ amp
Playback resumed.

$ amp
Stopping current song..
Now playing: Coldplay - Yellow [00:04:33]

$ amp yellow beatles -v
Stopping current song..
Now playing: the beatles- yellow submarine(LYRICS) [00:02:38]
Showing video in an external window.

$ ...
#+END_EXAMPLE

* Installation
** Requirements
- Python 3.3 or newer
- A up-to-date version of [[https://github.com/mpv-player/mpv][mpv]]


Once both of these requirements are met, amp can be installed from pip (with root privileges).
#+BEGIN_EXAMPLE
# pip install amp-player
#+END_EXAMPLE
* Planned features/fixes
- List multiple results to choose a song from
- Filter by duration
- Queue songs
- Song history
- Handle invalid options more gracefully
- When external dependency fails, show error output

* Troubleshooting
If playback ends abnormally before anything starts playing, it might be an issue with one of amp's dependencies.  Try using ==amp --verbose== to get the URL of the video, and then play the URL with mpv directly.  If that works, then please submit an issue (or pull request!).
